# Generated by Django 5.2.6 on 2026-09-21 16:46

import apps.candidates.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(blank=True, default='', max_length=50)),
                ('public_identity_mode', models.CharField(choices=[('ANONYMOUS', 'Anonymous'), ('DISPLAY_NAME', 'Display Name')], default='ANONYMOUS', max_length=12)),
                ('batch', models.CharField(max_length=10, validators=[apps.candidates.validators.validate_batch_year])),
                ('hiring_type', models.CharField(choices=[('PRIME', 'Prime'), ('DIGITAL', 'Digital'), ('NINJA', 'Ninja'), ('OTHER', 'Other')], max_length=10)),
                ('region', models.CharField(max_length=100)),
                ('interview_center', models.CharField(blank=True, default='', max_length=200)),
                ('interview_date', models.DateField(blank=True, null=True)),
                ('joining_location', models.CharField(blank=True, default='', max_length=200)),
                ('current_status', models.CharField(choices=[('REGISTERED', 'Registered'), ('INTERVIEWED', 'Interviewed'), ('SELECTED', 'Selected'), ('OFFER_RECEIVED', 'Offer Received'), ('READINESS_SURVEY', 'Readiness Survey'), ('WAITING_FOR_JOINING_LETTER', 'Waiting for Joining Letter'), ('JOINING_LETTER_RECEIVED', 'Joining Letter Received'), ('JOINING_DATE_RECEIVED', 'Joining Date Received'), ('JOINED', 'Joined'), ('WITHDRAWN', 'Withdrawn'), ('OTHER', 'Other')], default='REGISTERED', max_length=32)),
                ('offer_letter_date', models.DateField(blank=True, null=True)),
                ('expected_joining_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'candidate profile',
                'verbose_name_plural': 'candidate profiles',
                'indexes': [models.Index(fields=['batch'], name='idx_profile_batch'), models.Index(fields=['hiring_type'], name='idx_profile_hiring_type'), models.Index(fields=['region'], name='idx_profile_region'), models.Index(fields=['current_status'], name='idx_profile_status'), models.Index(fields=['joining_location'], name='idx_profile_join_loc'), models.Index(fields=['interview_date'], name='idx_profile_interview_dt'), models.Index(fields=['offer_letter_date'], name='idx_profile_offer_dt'), models.Index(fields=['expected_joining_date'], name='idx_profile_joining_dt')],
            },
        ),
    ]
