# Generated by Django 5.2.6 on 2026-09-21 12:06

import apps.accounts.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=apps.accounts.fields.CITextEmailField(max_length=254, unique=True),
        ),
    ]
