# Generated by Django 5.2.6 on 2026-09-23 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_timestamps'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='banned_until',
            field=models.DateTimeField(blank=True, help_text='Temporary suspension boundary (08 §6.1); NULL while banned = permanent', null=True),
        ),
    ]
