# Generated by Django 5.2.6 on 2026-09-22 18:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('SPAM', 'Spam or Commercial Promotion'), ('HARASSMENT', 'Harassment or Abuse'), ('MISINFORMATION', 'False Information / Rumors'), ('ABUSIVE_CONTENT', 'Profanity or Vulgarity'), ('PERSONAL_INFORMATION', 'Private Personal Information'), ('SCAM', 'Fraud or Fee Solicitation'), ('OTHER', 'Other Violation')], db_index=True, max_length=32)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('REVIEWED', 'Reviewed'), ('RESOLVED', 'Resolved (Action Taken)'), ('DISMISSED', 'Dismissed (No Violation)')], db_index=True, default='PENDING', max_length=16)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('moderator_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='community.comment')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='community.post')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_reports', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='idx_report_status_created'), models.Index(fields=['post', 'status'], name='idx_report_post_status'), models.Index(fields=['comment', 'status'], name='idx_report_comment_status')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('comment__isnull', True), ('post__isnull', False)), models.Q(('comment__isnull', False), ('post__isnull', True)), _connector='OR'), name='report_exactly_one_target'), models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('reporter', 'post'), name='unique_pending_report_per_post'), models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('reporter', 'comment'), name='unique_pending_report_per_comment')],
            },
        ),
    ]
