# Generated by Django 5.2.6 on 2026-09-21 18:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('INTERVIEW', 'Interview'), ('SELECTION', 'Selection'), ('OFFER_LETTER', 'Offer Letter'), ('READINESS_SURVEY', 'Readiness Survey'), ('JOINING_LETTER', 'Joining Letter'), ('JOINING_DATE', 'Joining Date'), ('JOINED', 'Joined'), ('OTHER', 'Other')], max_length=20)),
                ('event_date', models.DateField()),
                ('description', models.TextField(blank=True, default='')),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='candidates.candidateprofile')),
            ],
            options={
                'verbose_name': 'timeline event',
                'verbose_name_plural': 'timeline events',
                'ordering': ['-event_date', '-created_at'],
                'indexes': [models.Index(fields=['candidate', '-event_date'], name='idx_event_candidate_date'), models.Index(fields=['event_type', 'event_date'], name='idx_event_type_date')],
            },
        ),
    ]
