# Generated by Django 5.2.6 on 2026-09-22 10:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notify_on_comment', models.BooleanField(default=True, help_text='Notify when someone comments on your post')),
                ('notify_on_reply', models.BooleanField(default=True, help_text='Notify when someone replies to your comment')),
                ('notify_on_vote_milestone', models.BooleanField(default=True, help_text='Notify on post upvote milestones')),
                ('notify_on_announcements', models.BooleanField(default=True, help_text='Notify on admin community announcements')),
                ('notify_timeline_reminders', models.BooleanField(default=True, help_text='Periodic reminders to update timeline')),
                ('push_enabled', models.BooleanField(default=True, help_text='Global master toggle for browser push')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notification preference',
                'verbose_name_plural': 'notification preferences',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fcm_token', models.TextField(help_text='Firebase registration token', unique=True)),
                ('device_type', models.CharField(choices=[('WEB', 'Web Browser'), ('ANDROID', 'Android Web/PWA'), ('IOS', 'iOS Web/PWA'), ('OTHER', 'Other')], default='WEB', max_length=16)),
                ('browser', models.CharField(blank=True, default='', max_length=64)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'device',
                'verbose_name_plural': 'devices',
                'ordering': ['-last_seen_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='idx_device_user_active')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('COMMENT', 'New Comment'), ('REPLY', 'New Reply'), ('VOTE_MILESTONE', 'Upvote Milestone'), ('ANNOUNCEMENT', 'Announcement'), ('MODERATION', 'Moderation Alert'), ('TIMELINE_REMINDER', 'Timeline Reminder'), ('SYSTEM', 'System Alert')], db_index=True, default='SYSTEM', max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='community.comment')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='community.post')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', '-created_at'], name='idx_notif_recip_read_created'), models.Index(fields=['recipient', '-created_at'], name='idx_notif_recipient_created')],
                'constraints': [models.CheckConstraint(condition=models.Q(('is_read', False), ('read_at__isnull', False), _connector='OR'), name='notification_read_state')],
            },
        ),
    ]
